### ISSUE TITLE
Stop server exception

### ISSUE THREAD

**Issue by ProjectSky** [RoboTricker/Transport-Pipes#34]
* Server version: 1.12.1
* Transport-Pipes version: 4.2.0
* I stopped server, I got this error message.
```
[10:04:11] [TransportPipes Thread/INFO]: stopping TransportPipes-Thread
[10:04:11] [Server thread/ERROR]: Error occurred while disabling TransportPipes v4.2.0-b11 (Is it up to date?)
java.lang.NoSuchMethodError: org.jnbt.NBTOutputStream.<init>(Ljava/io/OutputStream;Lorg/jnbt/NBTCompression;)V
	at de.robotricker.transportpipes.saving.SavingManager.savePipesSync(SavingManager.java:100) ~[?:?]
	at de.robotricker.transportpipes.TransportPipes.onDisable(TransportPipes.java:226) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:348) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

* Start server message.
```
[10:08:44 ERROR]: Could not pass event WorldLoadEvent to TransportPipes v4.2.0-b11
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigo                                                                                                                        t-65e8124-8bf06d6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-                                                                                                                        65e8124-8bf06d6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigo                                                                                                                        t-65e8124-8bf06d6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigo                                                                                                                        t-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.12.1.jar:git-Spigot-65                                                                                                                        e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.1.jar:git-Spigot-65                                                                                                                        e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.1.jar:git-Spigot                                                                                                                        -65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.1.jar:git-Spigot-                                                                                                                        65e8124-8bf06d6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.jnbt.NBTInputStream.<init>(Ljava/io/InputStream;Lorg/jnbt/NBTCompression;                                                                                                                        )V
        at de.robotricker.transportpipes.saving.SavingManager.loadPipesSync(SavingManager.java:153) ~[?:?]
        at de.robotricker.transportpipes.saving.SavingManager.onWorldLoad(SavingManager.java:249) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigo                                                                                                                        t-65e8124-8bf06d6]
        ... 8 more
```

**Comment by sgdc3** [comment]
You changed the TransportPipes jar before stopping the server, please don't do that.

**Comment by RoboTricker** [comment]
Try to use the latest dev build: http://jenkins.frontfight.net/job/Transport-Pipes/lastSuccessfulBuild/artifact/target/transportpipes-4.2.2-SNAPSHOT.jar I will upload this on spigot soon.

**Comment by RoboTricker** [comment]
Is the error still happening and if so can you please test the new relase version 4.4.2 and tell me if it's still happening there?
