### ISSUE TITLE
Could not pass event InventoryClickEvent to TransportPipes

### ISSUE THREAD

**Issue by Vanilor** [RoboTricker/Transport-Pipes#36]
Hello when I start the server with the plugin installed everytime someone on the server clicks in an inventory this error gets put into the log:

`
[18:57:03 ERROR]: Could not pass event InventoryClickEvent to TransportPipes v4.2.2-SNAPSHOT-b46
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1815) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
        at de.robotricker.transportpipes.settings.SettingsInv.onInvClick(SettingsInv.java:74) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-31d3159]
        ... 15 
`

Happens both in the version 4.2.0 and in the 4.2.2-SNAPSHOT
Full startup log until the first time this error appears:
https://pastebin.com/HahrbL7q

**Comment by RoboTricker** [comment]
Thanks for the detailed bug report :) I Will fix this as soon as possible - I think it's just not yet fully compatible with 1.12.2

**Comment by RoboTricker** [comment]
Can you please test the new release version 4.2.2?

**Comment by Diniden** [comment]
I am still seeing this error with version 4.2.2-b58

```
Could not pass event InventoryClickEvent to TransportPipes v4.2.2-b58
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1820) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at de.robotricker.transportpipes.settings.SettingsInv.onInvClick(SettingsInv.java:80) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-c15d869]
	... 15 more
```

I'm on spigot 12.2.2

**Comment by RoboTricker** [comment]
Please give me the full server log :)

**Comment by Diniden** [comment]
Are you wanting the FULL server log or just something that expands the last 15 lines of the error?

If you want the latter, I could not find any log in my system that expands that. If you want the full server log, perhaps you can tell me what you need (I am a programmer) to help you out. The full server log has information about my users that I can't just dole out (or filter out).

**Comment by RoboTricker** [comment]
issue fixed
