### ISSUE TITLE
FileNotFoundException every 5 minutes

### ISSUE THREAD

**Issue by taberruu** [RoboTricker/Transport-Pipes#8]
Hey,
the plugin is displaying the following Exception:
`[08:35:54 WARN]: java.io.FileNotFoundException: ASkyGrid/pipes.dat (No such file or directory)
[08:35:54 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[08:35:54 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[08:35:54 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[08:35:54 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[08:35:54 WARN]:        at de.robotricker.transportpipes.a.a.a.a(Unknown Source)
[08:35:54 WARN]:        at de.robotricker.transportpipes.a.a.a.a(Unknown Source)
[08:35:54 WARN]:        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
[08:35:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:35:54 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[08:35:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[08:35:54 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:35:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[08:35:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[08:35:54 WARN]:        at net.minecraft.server.v1_11_R1.WorldServer.save(WorldServer.java:995)
[08:35:54 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.save(CraftWorld.java:748)
[08:35:54 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:703)
[08:35:54 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[08:35:54 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:35:54 INFO]: [TransportPipes] saved 0 pipes in 4 worlds`

**Comment by RoboTricker** [comment]
You can access the build with this bug fixed here: http://frontfight.net:8080/job/Transport-Pipes/lastSuccessfulBuild/artifact/target/transportpipes-3.5.1-SNAPSHOT.jar
